import { PRODUCT_ATTRIBUTES, SALES_MASTER_ATTRIBUTES } from '@interfaces/index';

export const SELECTED_ATTRIBUTES = {
  SALES_MASTER: [
    SALES_MASTER_ATTRIBUTES.name,
    SALES_MASTER_ATTRIBUTES.code,
    SALES_MASTER_ATTRIBUTES.transDate,
    SALES_MASTER_ATTRIBUTES.salesTotal,
    SALES_MASTER_ATTRIBUTES.paymentModeName,
    SALES_MASTER_ATTRIBUTES.customerName,
    SALES_MASTER_ATTRIBUTES.customerPhone,
    SALES_MASTER_ATTRIBUTES.customerEmail,
    SALES_MASTER_ATTRIBUTES.purchasedStatus,
    SALES_MASTER_ATTRIBUTES.purchasedTime,
  ],
  PRODUCT: [
    PRODUCT_ATTRIBUTES.name,
    PRODUCT_ATTRIBUTES.code,
    PRODUCT_ATTRIBUTES.image,
    PRODUCT_ATTRIBUTES.sellPrice,
    PRODUCT_ATTRIBUTES.unit,
    PRODUCT_ATTRIBUTES.productDiscount,
    PRODUCT_ATTRIBUTES.productTax,
  ],
};
